[general]
import = ["/home/spectro/.config/alacritty/theme_one_dark.toml"]

[window.dimensions]
columns = 120
lines = 36

[terminal.shell]
program = "/usr/bin/fish"
args = ["--init-command", "/usr/bin/tmux new -A -D -s main"]
