[general]
import = ["/home/spectro/.config/alacritty/theme_one_dark.toml"]

[window.dimensions]
columns = 120
lines = 36

[terminal.shell]
program = "/usr/bin/fish"
args = ["--init-command", "/usr/bin/tmux new -A -D -s main"]

[font]
size = 11.0

[cursor]
style.shape = "Beam"

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"
