#!/bin/bash

code --install-extension aaron-bond.better-comments
code --install-extension adpyke.codesnap
code --install-extension albymor.increment-selection
code --install-extension alexcvzz.vscode-sqlite
code --install-extension Angular.ng-template
code --install-extension bierner.github-markdown-preview
code --install-extension bierner.markdown-checkbox
code --install-extension bierner.markdown-emoji
code --install-extension bierner.markdown-footnotes
code --install-extension bierner.markdown-mermaid
code --install-extension bierner.markdown-preview-github-styles
code --install-extension bradlc.vscode-tailwindcss
code --install-extension christian-kohler.npm-intellisense
code --install-extension christian-kohler.path-intellisense
code --install-extension DaltonMenezes.aura-theme
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension dbaeumer.vscode-eslint
code --install-extension denoland.vscode-deno
code --install-extension eamodio.gitlens
code --install-extension ecmel.vscode-html-css
code --install-extension esbenp.prettier-vscode
code --install-extension formulahendry.auto-close-tag
code --install-extension formulahendry.auto-rename-tag
code --install-extension GitHub.copilot
code --install-extension GitHub.copilot-chat
code --install-extension github.vscode-github-actions
code --install-extension golang.go
code --install-extension Gruntfuggly.todo-tree
code --install-extension hashicorp.hcl
code --install-extension hbenl.vscode-mocha-test-adapter
code --install-extension hbenl.vscode-test-explorer
code --install-extension James-Yu.latex-workshop
code --install-extension mechatroner.rainbow-csv
code --install-extension mgmcdermott.vscode-language-babel
code --install-extension mikestead.dotenv
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-python.black-formatter
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-toolsai.vscode-jupyter-cell-tags
code --install-extension ms-toolsai.vscode-jupyter-slideshow
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.test-adapter-converter
code --install-extension mtxr.sqltools
code --install-extension nrwl.angular-console
code --install-extension oderwat.indent-rainbow
code --install-extension Orta.vscode-twoslash-queries
code --install-extension otovo-oss.htmx-tags
code --install-extension PKief.material-icon-theme
code --install-extension Prisma.prisma
code --install-extension redhat.vscode-yaml
code --install-extension rome.rome
code --install-extension rust-lang.rust-analyzer
code --install-extension serayuzgur.crates
code --install-extension sleistner.vscode-fileutils
code --install-extension softwaredotcom.swdc-vscode
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension streetsidesoftware.code-spell-checker-german
code --install-extension tamasfe.even-better-toml
code --install-extension valentjn.vscode-ltex
code --install-extension vscode-icons-team.vscode-icons
code --install-extension WallabyJs.console-ninja
code --install-extension wix.vscode-import-cost
code --install-extension yoavbls.pretty-ts-errors
code --install-extension zhuangtongfa.material-theme
code --install-extension Zignd.html-css-class-completion
code --install-extension ZixuanChen.vitest-explorer
