#!/bin/bash

code --install-extension a-h.templ
code --install-extension aaron-bond.better-comments
code --install-extension adpyke.codesnap
code --install-extension albymor.increment-selection
code --install-extension alexcvzz.vscode-sqlite
code --install-extension bierner.github-markdown-preview
code --install-extension bierner.markdown-checkbox
code --install-extension bierner.markdown-emoji
code --install-extension bierner.markdown-footnotes
code --install-extension bierner.markdown-mermaid
code --install-extension bierner.markdown-preview-github-styles
code --install-extension bierner.markdown-yaml-preamble
code --install-extension bradlc.vscode-tailwindcss
code --install-extension christian-kohler.npm-intellisense
code --install-extension christian-kohler.path-intellisense
code --install-extension davidanson.vscode-markdownlint
code --install-extension dbaeumer.vscode-eslint
code --install-extension denoland.vscode-deno
code --install-extension digitalbrainstem.javascript-ejs-support
code --install-extension devsense.composer-php-vscode
code --install-extension devsense.intelli-php-vscode
code --install-extension devsense.phptools-vscode
code --install-extension devsense.profiler-php-vscode
code --install-extension eamodio.gitlens
code --install-extension ecmel.vscode-html-css
code --install-extension esbenp.prettier-vscode
code --install-extension formulahendry.auto-close-tag
code --install-extension formulahendry.auto-rename-tag
code --install-extension github.copilot
code --install-extension github.copilot-chat
code --install-extension github.vscode-github-actions
code --install-extension golang.go
code --install-extension gruntfuggly.todo-tree
code --install-extension hashicorp.hcl
code --install-extension james-yu.latex-workshop
code --install-extension mechatroner.rainbow-csv
code --install-extension mgmcdermott.vscode-language-babel
code --install-extension mikestead.dotenv
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-python.black-formatter
code --install-extension ms-python.debugpy
code --install-extension ms-python.python
code --install-extension ms-vscode.cpptools
code --install-extension mtxr.sqltools
code --install-extension orta.vscode-twoslash-queries
code --install-extension otovo-oss.htmx-tags
code --install-extension ph0enixkm.amber-language
code --install-extension platformio.platformio-ide
code --install-extension prisma.prisma
code --install-extension redhat.vscode-yaml
code --install-extension rust-lang.rust-analyzer
code --install-extension serayuzgur.crates
code --install-extension sleistner.vscode-fileutils
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension streetsidesoftware.code-spell-checker-german
code --install-extension svelte.svelte-vscode
code --install-extension tamasfe.even-better-toml
code --install-extension usernamehw.errorlens
code --install-extension valentjn.vscode-ltex
code --install-extension vitest.explorer
code --install-extension vscode-icons-team.vscode-icons
code --install-extension wallabyjs.console-ninja
code --install-extension yoavbls.pretty-ts-errors
code --install-extension zhuangtongfa.material-theme
code --install-extension zignd.html-css-class-completion
